@echo off
echo Pretend loading...
timeout /t 1 /nobreak
echo Exiting...
echo Testing your patience...
echo Loading File 1/30...
timeout /t 1 /nobreak
echo Loading File 2/30...
timeout /t 1 /nobreak
echo Loading File 3/30...
timeout /t 1 /nobreak
echo Loading File 4/30...
timeout /t 1 /nobreak
echo Loading File 5/30...
timeout /t 1 /nobreak
echo Loading File 6/30...
timeout /t 1 /nobreak
echo Loading File 7/30...
timeout /t 1 /nobreak
echo Loading File 8/30...
timeout /t 1 /nobreak
echo Loading File 9/30...
timeout /t 1 /nobreak
echo Loading File 10/30...
timeout /t 1 /nobreak
echo Loading File 11/30...
timeout /t 1 /nobreak
echo Loading File 12/30...
timeout /t 1 /nobreak
echo Loading File 13/30...
timeout /t 1 /nobreak
echo Loading File 14/30...
timeout /t 1 /nobreak
echo Loading File 15/30...
timeout /t 1 /nobreak
echo Loading File 16/30...
timeout /t 1 /nobreak
echo Loading File 17/30...
timeout /t 1 /nobreak
echo Loading File 18/30...
timeout /t 1 /nobreak
echo Loading File 19/30...
timeout /t 1 /nobreak
echo Loading File 20/30...
timeout /t 1 /nobreak
echo Loading File 21/30...
timeout /t 1 /nobreak
echo Loading File 22/30...
timeout /t 1 /nobreak
echo Loading File 23/30...
timeout /t 1 /nobreak
echo Loading File 24/30...
timeout /t 1 /nobreak
echo Loading File 25/30...
timeout /t 1 /nobreak
echo Loading File 26/30...
timeout /t 1 /nobreak
echo Loading File 27/30...
timeout /t 1 /nobreak
echo Loading File 28/30...
timeout /t 1 /nobreak
echo Loading File 29/30...
timeout /t 1 /nobreak
echo Loading File 30/30...
timeout /t 30 /nobreak
echo Loading...
echo Loading...
echo Loading...
echo Executing...
timeout /t 1 /nobreak
timeout /t 1 /nobreak
timeout /t 1 /nobreak
timeout /t 1 /nobreak
timeout /t 1 /nobreak
timeout /t 1 /nobreak
echo Done!
cd ..
cd ..
